apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: 4877005032ac2bb7e85ed148960dfa915fdcdf06
    app.openshift.io/vcs-uri: https://github.com/rainshuzi/web-client
    kompose.cmd: /usr/local/bin/kompose convert -o k8s
    kompose.version: 1.24.0 (HEAD)
  creationTimestamp: null
  labels:
    app: tekton-squad-1-project
    app.kubernetes.io/instance: tekton-squad-1-project
    app.kubernetes.io/name: tekton-squad-1-project-web-client
    io.kompose.service: web-client
  name: web-client
spec:
  ports:
  - Protocol: TCP
    name: "80"
    port: 80
    targetPort: 3000
  selector:
    app: tekton-squad-1-project
    app.kubernetes.io/instance: tekton-squad-1-project
    app.kubernetes.io/name: tekton-squad-1-project-web-client
    io.kompose.service: web-client
status:
  loadBalancer: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    app.openshift.io/vcs-ref: 4877005032ac2bb7e85ed148960dfa915fdcdf06
    app.openshift.io/vcs-uri: https://github.com/rainshuzi/web-client
  creationTimestamp: null
  labels:
    app: tekton-squad-1-project
    app.kubernetes.io/instance: tekton-squad-1-project
    app.kubernetes.io/name: tekton-squad-1-project-web-client
    io.kompose.service: notused
  name: notused
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    app.openshift.io/vcs-ref: 4877005032ac2bb7e85ed148960dfa915fdcdf06
    app.openshift.io/vcs-uri: https://github.com/rainshuzi/web-client
  creationTimestamp: null
  labels:
    app: tekton-squad-1-project
    app.kubernetes.io/instance: tekton-squad-1-project
    app.kubernetes.io/name: tekton-squad-1-project-web-client
    io.kompose.service: web-client-claim0
  name: web-client-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    app.openshift.io/vcs-ref: 4877005032ac2bb7e85ed148960dfa915fdcdf06
    app.openshift.io/vcs-uri: https://github.com/rainshuzi/web-client
  creationTimestamp: null
  labels:
    app: tekton-squad-1-project
    app.kubernetes.io/instance: tekton-squad-1-project
    app.kubernetes.io/name: tekton-squad-1-project-web-client
    io.kompose.service: web-client-claim1
  name: web-client-claim1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    app.openshift.io/vcs-ref: 4877005032ac2bb7e85ed148960dfa915fdcdf06
    app.openshift.io/vcs-uri: https://github.com/rainshuzi/web-client
  creationTimestamp: null
  labels:
    app: tekton-squad-1-project
    app.kubernetes.io/instance: tekton-squad-1-project
    app.kubernetes.io/name: tekton-squad-1-project-web-client
    io.kompose.service: web-client-claim2
  name: web-client-claim2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: 4877005032ac2bb7e85ed148960dfa915fdcdf06
    app.openshift.io/vcs-uri: https://github.com/rainshuzi/web-client
    kompose.cmd: /usr/local/bin/kompose convert -o k8s
    kompose.version: 1.24.0 (HEAD)
  creationTimestamp: null
  labels:
    app: tekton-squad-1-project
    app.kubernetes.io/instance: tekton-squad-1-project
    app.kubernetes.io/name: tekton-squad-1-project-web-client
    io.kompose.service: web-client
  name: web-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tekton-squad-1-project
      app.kubernetes.io/instance: tekton-squad-1-project
      app.kubernetes.io/name: tekton-squad-1-project-web-client
      io.kompose.service: web-client
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-ref: 4877005032ac2bb7e85ed148960dfa915fdcdf06
        app.openshift.io/vcs-uri: https://github.com/rainshuzi/web-client
        kompose.cmd: /usr/local/bin/kompose convert -o k8s
        kompose.version: 1.24.0 (HEAD)
      creationTimestamp: null
      labels:
        app: tekton-squad-1-project
        app.kubernetes.io/instance: tekton-squad-1-project
        app.kubernetes.io/name: tekton-squad-1-project-web-client
        io.kompose.network/boilerplate-network: "true"
        io.kompose.service: web-client
    spec:
      containers:
      - image: quay.io/jian_ping_shu/next_js:4877005032ac2bb7e85ed148960dfa915fdcdf06
        name: web-client
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
      volumes:
      - name: web-client-claim0
        persistentVolumeClaim:
          claimName: web-client-claim0
      - name: web-client-claim1
        persistentVolumeClaim:
          claimName: web-client-claim1
      - name: web-client-claim2
        persistentVolumeClaim:
          claimName: web-client-claim2
      - name: notused
        persistentVolumeClaim:
          claimName: notused
status: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    app.openshift.io/vcs-ref: 4877005032ac2bb7e85ed148960dfa915fdcdf06
    app.openshift.io/vcs-uri: https://github.com/rainshuzi/web-client
  creationTimestamp: null
  labels:
    app: tekton-squad-1-project
    app.kubernetes.io/instance: tekton-squad-1-project
    app.kubernetes.io/name: tekton-squad-1-project-web-client
  name: boilerplate-network
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: tekton-squad-1-project
          app.kubernetes.io/instance: tekton-squad-1-project
          app.kubernetes.io/name: tekton-squad-1-project-web-client
          io.kompose.network/boilerplate-network: "true"
  podSelector:
    matchLabels:
      app: tekton-squad-1-project
      app.kubernetes.io/instance: tekton-squad-1-project
      app.kubernetes.io/name: tekton-squad-1-project-web-client
      io.kompose.network/boilerplate-network: "true"
