apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: 2ec148889a65660251e00851d8121d2840537db1
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/apac-4-squad-6-frontend
  labels:
    app: squad-6
    app.kubernetes.io/instance: squad-6
    app.kubernetes.io/name: squad-6-apac-4-squad-6-frontend
    app.openshift.io/runtime: js
  name: apac-4-squad-6-frontend
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: squad-6
    app.kubernetes.io/instance: squad-6
    app.kubernetes.io/name: squad-6-apac-4-squad-6-frontend
    app.openshift.io/runtime: js
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: 2ec148889a65660251e00851d8121d2840537db1
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/apac-4-squad-6-frontend
  labels:
    app: squad-6
    app.kubernetes.io/instance: squad-6
    app.kubernetes.io/name: squad-6-apac-4-squad-6-frontend
    app.openshift.io/runtime: js
  name: apac-4-squad-6-frontend
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: squad-6
      app.kubernetes.io/instance: squad-6
      app.kubernetes.io/name: squad-6-apac-4-squad-6-frontend
      app.openshift.io/runtime: js
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-ref: 2ec148889a65660251e00851d8121d2840537db1
        app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/apac-4-squad-6-frontend
      labels:
        app: squad-6
        app.kubernetes.io/instance: squad-6
        app.kubernetes.io/name: squad-6-apac-4-squad-6-frontend
        app.openshift.io/runtime: js
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/dineshbarai/squad-6-frontend:2ec148889a65660251e00851d8121d2840537db1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: apac-4-squad-6-frontend
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-ref: 2ec148889a65660251e00851d8121d2840537db1
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/apac-4-squad-6-frontend
    argocd.argoproj.io/sync-options: Validate=false
    openshift.io/host.generated: "true"
  labels:
    app: squad-6
    app.kubernetes.io/instance: squad-6
    app.kubernetes.io/name: squad-6-apac-4-squad-6-frontend
    app.openshift.io/runtime: js
  name: apac-4-squad-6-frontend
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: apac-4-squad-6-frontend
    weight: 100
  wildcardPolicy: None
