apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: 347a5c9d86b64f2b2aa4c2a8608bf5526e7d69b2
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/apac-4-squad-6-backend
  labels:
    app: squad-6
    app.kubernetes.io/instance: squad-6
    app.kubernetes.io/name: squad-6-voting-service
    app.openshift.io/runtime: js
  name: voting-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 4000
  selector:
    app: squad-6
    app.kubernetes.io/instance: squad-6
    app.kubernetes.io/name: squad-6-voting-service
    app.openshift.io/runtime: js
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: 347a5c9d86b64f2b2aa4c2a8608bf5526e7d69b2
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/apac-4-squad-6-backend
  labels:
    app: squad-6
    app.kubernetes.io/instance: squad-6
    app.kubernetes.io/name: squad-6-voting-service
    app.openshift.io/runtime: js
  name: voting-service
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: squad-6
      app.kubernetes.io/instance: squad-6
      app.kubernetes.io/name: squad-6-voting-service
      app.openshift.io/runtime: js
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-ref: 347a5c9d86b64f2b2aa4c2a8608bf5526e7d69b2
        app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/apac-4-squad-6-backend
      labels:
        app: squad-6
        app.kubernetes.io/instance: squad-6
        app.kubernetes.io/name: squad-6-voting-service
        app.openshift.io/runtime: js
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/dineshbarai/squad-6-backend:347a5c9d86b64f2b2aa4c2a8608bf5526e7d69b2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health-check
            port: 4000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: voting-service
        ports:
        - containerPort: 4000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-ref: 347a5c9d86b64f2b2aa4c2a8608bf5526e7d69b2
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/apac-4-squad-6-backend
    argocd.argoproj.io/sync-options: Validate=false
    openshift.io/host.generated: "true"
  labels:
    app: squad-6
    app.kubernetes.io/instance: squad-6
    app.kubernetes.io/name: squad-6-voting-service
    app.openshift.io/runtime: js
  name: voting-service
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: voting-service
    weight: 100
  wildcardPolicy: None
