apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: 9b3fe7570242b6ed81f1f02482ca04902fce0f03
    app.openshift.io/vcs-uri: https://github.com/rainshuzi/node-app
    kompose.cmd: /usr/local/bin/kompose convert -o k8s
    kompose.version: 1.24.0 (HEAD)
  creationTimestamp: null
  labels:
    app: tekton-squad-1-project
    app.kubernetes.io/instance: tekton-squad-1-project
    app.kubernetes.io/name: tekton-squad-1-project-node-app
    io.kompose.service: mysql-db
  name: mysql-db
spec:
  ports:
  - Protocol: TCP
    name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    app: tekton-squad-1-project
    app.kubernetes.io/instance: tekton-squad-1-project
    app.kubernetes.io/name: tekton-squad-1-project-node-app
    io.kompose.service: mysql-db
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: 9b3fe7570242b6ed81f1f02482ca04902fce0f03
    app.openshift.io/vcs-uri: https://github.com/rainshuzi/node-app
    kompose.cmd: /usr/local/bin/kompose convert -o k8s
    kompose.version: 1.24.0 (HEAD)
  creationTimestamp: null
  labels:
    app: tekton-squad-1-project
    app.kubernetes.io/instance: tekton-squad-1-project
    app.kubernetes.io/name: tekton-squad-1-project-node-app
    io.kompose.service: node-app
  name: node-app
spec:
  ports:
  - Protocol: TCP
    name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    app: tekton-squad-1-project
    app.kubernetes.io/instance: tekton-squad-1-project
    app.kubernetes.io/name: tekton-squad-1-project-node-app
    io.kompose.service: node-app
status:
  loadBalancer: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    app.openshift.io/vcs-ref: 9b3fe7570242b6ed81f1f02482ca04902fce0f03
    app.openshift.io/vcs-uri: https://github.com/rainshuzi/node-app
  creationTimestamp: null
  labels:
    app: tekton-squad-1-project
    app.kubernetes.io/instance: tekton-squad-1-project
    app.kubernetes.io/name: tekton-squad-1-project-node-app
    io.kompose.service: db-data
  name: db-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    app.openshift.io/vcs-ref: 9b3fe7570242b6ed81f1f02482ca04902fce0f03
    app.openshift.io/vcs-uri: https://github.com/rainshuzi/node-app
  creationTimestamp: null
  labels:
    app: tekton-squad-1-project
    app.kubernetes.io/instance: tekton-squad-1-project
    app.kubernetes.io/name: tekton-squad-1-project-node-app
    io.kompose.service: node-app-claim0
  name: node-app-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    app.openshift.io/vcs-ref: 9b3fe7570242b6ed81f1f02482ca04902fce0f03
    app.openshift.io/vcs-uri: https://github.com/rainshuzi/node-app
  creationTimestamp: null
  labels:
    app: tekton-squad-1-project
    app.kubernetes.io/instance: tekton-squad-1-project
    app.kubernetes.io/name: tekton-squad-1-project-node-app
    io.kompose.service: node-app-claim1
  name: node-app-claim1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    app.openshift.io/vcs-ref: 9b3fe7570242b6ed81f1f02482ca04902fce0f03
    app.openshift.io/vcs-uri: https://github.com/rainshuzi/node-app
  creationTimestamp: null
  labels:
    app: tekton-squad-1-project
    app.kubernetes.io/instance: tekton-squad-1-project
    app.kubernetes.io/name: tekton-squad-1-project-node-app
    io.kompose.service: node-app-claim2
  name: node-app-claim2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    app.openshift.io/vcs-ref: 9b3fe7570242b6ed81f1f02482ca04902fce0f03
    app.openshift.io/vcs-uri: https://github.com/rainshuzi/node-app
  creationTimestamp: null
  labels:
    app: tekton-squad-1-project
    app.kubernetes.io/instance: tekton-squad-1-project
    app.kubernetes.io/name: tekton-squad-1-project-node-app
    io.kompose.service: notused
  name: notused
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: 9b3fe7570242b6ed81f1f02482ca04902fce0f03
    app.openshift.io/vcs-uri: https://github.com/rainshuzi/node-app
    kompose.cmd: /usr/local/bin/kompose convert -o k8s
    kompose.version: 1.24.0 (HEAD)
  creationTimestamp: null
  labels:
    app: tekton-squad-1-project
    app.kubernetes.io/instance: tekton-squad-1-project
    app.kubernetes.io/name: tekton-squad-1-project-node-app
    io.kompose.service: node-app
  name: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tekton-squad-1-project
      app.kubernetes.io/instance: tekton-squad-1-project
      app.kubernetes.io/name: tekton-squad-1-project-node-app
      io.kompose.service: node-app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-ref: 9b3fe7570242b6ed81f1f02482ca04902fce0f03
        app.openshift.io/vcs-uri: https://github.com/rainshuzi/node-app
        kompose.cmd: /usr/local/bin/kompose convert -o k8s
        kompose.version: 1.24.0 (HEAD)
      creationTimestamp: null
      labels:
        app: tekton-squad-1-project
        app.kubernetes.io/instance: tekton-squad-1-project
        app.kubernetes.io/name: tekton-squad-1-project-node-app
        io.kompose.network/boilerplate-network: "true"
        io.kompose.service: node-app
    spec:
      containers:
      - image: quay.io/jian_ping_shu/next_js:9b3fe7570242b6ed81f1f02482ca04902fce0f03
        name: node-app
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
      volumes:
      - name: node-app-claim0
        persistentVolumeClaim:
          claimName: node-app-claim0
      - name: node-app-claim1
        persistentVolumeClaim:
          claimName: node-app-claim1
      - name: node-app-claim2
        persistentVolumeClaim:
          claimName: node-app-claim2
      - name: notused
        persistentVolumeClaim:
          claimName: notused
status: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    app.openshift.io/vcs-ref: 9b3fe7570242b6ed81f1f02482ca04902fce0f03
    app.openshift.io/vcs-uri: https://github.com/rainshuzi/node-app
  creationTimestamp: null
  labels:
    app: tekton-squad-1-project
    app.kubernetes.io/instance: tekton-squad-1-project
    app.kubernetes.io/name: tekton-squad-1-project-node-app
  name: boilerplate-network
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: tekton-squad-1-project
          app.kubernetes.io/instance: tekton-squad-1-project
          app.kubernetes.io/name: tekton-squad-1-project-node-app
          io.kompose.network/boilerplate-network: "true"
  podSelector:
    matchLabels:
      app: tekton-squad-1-project
      app.kubernetes.io/instance: tekton-squad-1-project
      app.kubernetes.io/name: tekton-squad-1-project-node-app
      io.kompose.network/boilerplate-network: "true"
